name: notifly_flutter_android
description: Android implementation of the notifly_flutter plugin
version: 0.1.1
homepage: https://notifly.tech/
publish_to: https://pub.dev

environment:
  sdk: ">=2.19.0 <4.0.0"

flutter:
  plugin:
    implements: notifly_flutter
    platforms:
      android:
        package: tech.notifly
        pluginClass: NotiflyFlutterPlugin
        dartPluginClass: NotiflyFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  notifly_flutter_platform_interface:
    path: ../notifly_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
