name: notifly_flutter_android
description: Android implementation of the notifly_flutter plugin, based on Notifly Android SDK.
version: 1.1.3
homepage: https://notifly.tech/

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: notifly_flutter
    platforms:
      android:
        package: tech.notifly
        pluginClass: NotiflyFlutterPlugin
        dartPluginClass: NotiflyFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  notifly_flutter_platform_interface: 1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
