name: notifly_flutter_ios
description: iOS implementation of the notifly_flutter plugin, based on Notifly iOS SDK.
version: 1.2.2
homepage: https://notifly.tech/

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: notifly_flutter
    platforms:
      ios:
        pluginClass: NotiflyFlutterPlugin
        dartPluginClass: NotiflyFlutterIOS

dependencies:
  flutter:
    sdk: flutter
  notifly_flutter_platform_interface: 1.2.2

dev_dependencies:
  dart_style: ^2.2.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
