name: notifly_flutter_ios
description: iOS implementation of the notifly_flutter plugin, based on Notifly iOS SDK.
# version: 1.9.0
homepage: https://notifly.tech/

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: notifly_flutter
    platforms:
      ios:
        pluginClass: NotiflyFlutterPlugin
        dartPluginClass: NotiflyFlutterIOS

dependencies:
  flutter:
    sdk: flutter
  # notifly_flutter_platform_interface: 1.9.0 # Remove this line if you wish to locally test this package
  notifly_flutter_platform_interface: # Remove this line if you wish to publish to pub.dev
    path: ../notifly_flutter_platform_interface # Remove this line if you wish to publish to pub.dev

dev_dependencies:
  dart_style: ^2.2.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
