name: notifly_flutter_web
description: Notifly website SDK for notifly_flutter plugin

version: 1.3.3
homepage: https://notifly.tech/

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: notifly_flutter
    platforms:
      web:
        pluginClass: NotiflyFlutterWeb
        fileName: notifly_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  notifly_flutter_platform_interface: 1.3.3 # Remove this line if you wish to locally test this package

  # notifly_flutter_platform_interface: # Remove this line if you wish to publish to pub.dev
  #   path: ../notifly_flutter_platform_interface # Remove this line if you wish to publish to pub.dev

dev_dependencies:
  dart_style: ^2.2.1
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
