name: notifly_flutter_platform_interface
description: A common platform interface for the notifly_flutter plugin, the app-facing package.
version: 1.1.5
homepage: https://notifly.tech/

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
