name: notifly_flutter
description: Notifly Flutter Plugin is a cross-platform SDK for integrating Notifly services into your Flutter apps.
version: 1.2.3
homepage: https://notifly.tech/

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: notifly_flutter_android
      ios:
        default_package: notifly_flutter_ios
      web:
        default_package: notifly_flutter_web

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  notifly_flutter_android: 1.2.3
  notifly_flutter_ios: 1.2.3
  notifly_flutter_web: 1.2.3
  notifly_flutter_platform_interface: 1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
