name: notifly_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/notifly_flutter.yaml"
      - "notifly_flutter/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/notifly_flutter.yaml"
      - "notifly_flutter/**"

env:
  VERY_GOOD_CLI_TELEMETRY: "false"
  CI: "true"
  GIT_TERMINAL_PROMPT: "0"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notifly_flutter
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.10.0
          cache: true

      - name: ğŸ“¦ Install Dependencies
        run: |
          dart --disable-analytics
          flutter --disable-telemetry
          flutter pub get

      - name: âœ¨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: ğŸ•µï¸ Analyze
        run: flutter analyze lib test

      - name: ğŸ§ª Run Tests
        run: flutter test --coverage --test-randomize-ordering-seed random

  android:
    runs-on: macos-latest
    if: false # TODO: Integration tests are flaky, see https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/79

    defaults:
      run:
        working-directory: notifly_flutter/example

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Disable analytics/telemetry
        run: |
          dart --disable-analytics || true
          flutter --disable-telemetry || true

      - name: Flutter Doctor
        run: flutter doctor -v

  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: notifly_flutter/example

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Disable analytics/telemetry
        run: |
          dart --disable-analytics || true
          flutter --disable-telemetry || true

      - name: Flutter Doctor
        run: flutter doctor -v
