name: notifly_flutter_platform_interface

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/notifly_flutter_platform_interface.yaml"
      - "notifly_flutter_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/notifly_flutter_platform_interface.yaml"
      - "notifly_flutter_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.7.0
      working_directory: notifly_flutter_platform_interface
      min_coverage: 0

