name: notifly_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/notifly_flutter.yaml"
      - "notifly_flutter/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/notifly_flutter.yaml"
      - "notifly_flutter/**"

env:
  VERY_GOOD_CLI_TELEMETRY: "false"
  CI: "true"
  GIT_TERMINAL_PROMPT: "0"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.18.0
    with:
      flutter_channel: stable
      flutter_version: 3.10.0
      working_directory: notifly_flutter
      min_coverage: 0
      setup: |        
        dart --disable-analytics || true
        flutter --disable-telemetry || true
        mkdir -p ~/.very_good && printf '{"telemetry":false}\n' > ~/.very_good/config.json || true

        printf 'n\n' | script -q -e -c "flutter pub global activate very_good_cli" /dev/null
    secrets: inherit

  android:
    runs-on: macos-latest
    if: false # TODO: Integration tests are flaky, see https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/79

    defaults:
      run:
        working-directory: notifly_flutter/example

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Disable analytics/telemetry
        run: |
          dart --disable-analytics || true
          flutter --disable-telemetry || true

      - name: Flutter Doctor
        run: flutter doctor -v

  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: notifly_flutter/example

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Disable analytics/telemetry
        run: |
          dart --disable-analytics || true
          flutter --disable-telemetry || true

      - name: Flutter Doctor
        run: flutter doctor -v
