name: notifly_flutter_ios

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/notifly_flutter_ios.yaml"
      - "notifly_flutter_ios/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/notifly_flutter_ios.yaml"
      - "notifly_flutter_ios/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notifly_flutter_ios
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.10.0
          cache: true

      - name: ğŸ“¦ Install Dependencies
        run: |
          dart --disable-analytics
          flutter --disable-telemetry
          flutter pub get

      - name: âœ¨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: ğŸ•µï¸ Analyze
        run: flutter analyze lib test

      - name: ğŸ§ª Run Tests
        run: flutter test --coverage --test-randomize-ordering-seed random

